### ISSUE TITLE
Site innacessible

### ISSUE THREAD

**Issue by flomalherbe** [flomalherbe/florent-malherbe-blog#1]
Bonjour,

mon site internet m'affiche une erreur 404, et je ne comprends pas comment y accéder. Pourriez vous m'aider? Merci

https://flomalherbe.github.io/florent-malherbe-blog/

**Comment by GuyliannEngels** [comment]
Bonjour @flomalherbe ,

Tu me nomme collaborateur de ton travail directement et tu ouvre une issue sans me notifier dans cette dernière. Tu as de la chance que j'ai ouvert ton dépôt afin d'y jeter un oeil sinon je ne me serais même pas rendu compte que tu avais ouvert une issue.

j'y regarde

**Comment by GuyliannEngels** [comment]
Je ne vois pas de problème particulier en local. Ton site me semble OK. j'ai tout de même réalisé un *commit* donc avant de faire quoi que ce soit, n'oublie pas de faire un PULL.

Si ton problème ne provient pas de ton site qui tourne très bien en local. Il provient peut être de la modification des paramètres sur GITHUB. As tu bien dans la section GitHub pages modifié les paramètres comme montré dans le tutoriel ?

**Comment by flomalherbe** [comment]
C'était effectivement l'étape du settings que j'avais oublié de faire. Merci d'avoir pris mon problème en considération et désolé de ne pas vous avoir notifié dans l'issue.
Bonne journée

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by GuyliannEngels** [comment]
c'est une bonne nouvelle. Nous pouvons donc clôturer cette ISSUE. En cas de nouveaux problèmes que tu ne peux résoudre seul ou avec tes collègues de cours, n'hésite pas à créer une nouvelles issue en notifiant les personnes que tu souhaites interroger.
